apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcr-service-account
secrets:
- name: gcr-registry-credentials
imagePullSecrets:
- name: gcr-registry-credentials
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: lightshow-server-image
spec:
  tag: us.gcr.io/pgtm-gwestenberg-151319/lightshow-server
  serviceAccount: gcr-service-account
  builder:
    name: my-builder
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/guidowb/lightshow-server
      revision: main
