apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: lightshow-api
spec:
  virtualhost:
    fqdn: api.lightshow.guidowb.online
    tls:
      secretName: lightshow-certificate
  routes:
    - services:
        - name: lightshow-server
          port: 8080
      enableWebsockets: true
---
apiVersion: v1
kind: Service
metadata:
  name: lightshow-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: lightshow-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightshow-server
  labels:
    app: lightshow-server
spec:
  selector:
    matchLabels:
      app: lightshow-server
  template:
    metadata:
      labels:
        app: lightshow-server
    spec:
      imagePullSecrets:
      - name: gcr.io.pullsecret
      containers:
      - name: lightshow-server
        image: us.gcr.io/pgtm-gwestenberg-151319/lightshow-server
